apiVersion: v1
kind: Service
metadata:
  name: {{ include "uhre-bo.fullname" . }}
  labels:
    app: {{ include "uhre-bo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.serverPort }}
      targetPort: {{ .Values.service.serverPort }}
      protocol: TCP
      name: server
  selector:
    app: {{ include "uhre-bo.fullname" . }}
