apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uhre-cron.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ include "uhre-cron.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "uhre-cron.name" . }}
    spec:
      imagePullSecrets:
        - name: artifactory-reader
      #volumes:
      #  - name: cron-config-volume
      #    configMap:
      #      name: cron-config
      #  - name: celery-config-volume
      #    configMap:
      #      name: celery-config
      containers:
        - name: uhre-cron
          image: geocomply.jfrog.io/apps-uhre-bo-docker-dev-local/uhre-cron:{{ .Values.cronimage.tag }}
          imagePullPolicy: {{ .Values.cronimage.pullPolicy }}
          command: ["/bin/sh"]
          # args: ["-c", "while true; do echo 1234567890; sleep 3600;done"]
          args: ["-c", "touch /tmp/cron.log && /cron-start.sh"]
          envFrom:
            - configMapRef:
                name: {{ include "uhre-cron.name" . }}-env
          #volumeMounts:
          #  - name: cron-config-volume
          #    mountPath: "/app/config.yaml"
          #    subPath: "config.yaml"
          #  - name: celery-config-volume
          #    mountPath: "/app/celery_config.py"
          #    subPath: "celery_config.py"