{{- $fullName := include "Magl.fullname" . -}}
{{- $instances := dict "author" .Values.magnoliaAuthor "public" .Values.magnoliaPublic }}
{{- if $value.enabled }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "Magl.fullname" . }}
spec:
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ include "Magl.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "Magl.fullname" . }}
    spec:
      volumes:
        - name: server-config-volume
          configMap:
            name: server-config
        - name: setenv-config-volume
          configMap:
            name: setenv-config
        - name: publishing-volume
          configMap:
            name: publishing-config
        - name: jackcrx-config-volume
          configMap:
            name: jackrabbit-config
        
      initcontainer:

      containers:
        - name: author
          image: :{{ .Values.magnoliaAuthor.tag }}
          imagePullPolicy: {{ .Values.magnoliaAuthor.pullPolicy }}
          command: ["/bin/sh"]
          # args: ["-c", "while true; do echo 1234567890; sleep 3600;done"]
          args: ["-c", "/beat-start.sh"]
          envFrom:
            - configMapRef:
                name: {{ include "Magl.fullname" . }}-env
          #volumeMounts:
          #  - name: cron-config-volume
          #    mountPath: "/app/config.yaml"
          #    subPath: "config.yaml"
          #  - name: celery-config-volume
          #    mountPath: "/app/celery_config.py"
          #    subPath: "celery_config.py"