apiVersion: v1
kind: Service
metadata:
  name: {{ include "Magl.fullname" . }}
  labels:
    {{- include "Magl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  Nodeports: {{ $.Values.service.NodePort }}
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "Magl.selectorLabels" . | nindent 4 }}
