variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

# https://forum.gitlab.com/t/docker-dind-stops-working-after-12-1-0-update/28664/3
services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - test
  - deploy

lint:
  stage: test
  image:
    name: alpine/helm:3.0.3
    entrypoint: [""]
  script:
    - helm lint

upload:
  stage: deploy
  image:
    name: registry.gitlab.com/mironet/helm-kubectl-gomplate
    entrypoint: [""]
  before_script:
    - apk add curl
    - export GIT_TAG=$(git describe --always)
    - export CHART_VERSION=$GIT_TAG
  script:
    - cat .Chart.tpl | gomplate > Chart.yaml
    - cat Chart.yaml
    - helm dep build
    - helm package .
    - ls -1 magnolia-helm*.tgz | while read i; do curl -u "$CHARTMUSEUM_USER:$CHARTMUSEUM_PASS" --data-binary @$i https://charts.mirohost.ch/api/charts; done
  only:
    - tags
