variables: {}

stages:
  - lint
  - test
  - deploy

.test_before: &test_before
    - export GIT_TAG=$(git describe --always)
    - export CHART_VERSION=$GIT_TAG
    - cat .Chart.tpl | gomplate > Chart.yaml
    - cat Chart.yaml

.test_after: &test_after
    - helm del ${RELEASE}
    - kubectl get pods -l component=test -l app.kubernetes.io/instance=${RELEASE} -o json | kubectl delete -f -
    - kubectl get persistentvolumeclaims -l "release=${RELEASE}" -o json | kubectl delete -f -

lint:
  stage: lint
  image:
    name: registry.gitlab.com/mironet/helm-kubectl-gomplate
    entrypoint: [""]
  before_script:
    - *test_before
  script:
    - helm lint

test-simple:
  stage: test
  image:
    name: registry.gitlab.com/mironet/helm-kubectl-gomplate
    entrypoint: [""]
  before_script:
    - *test_before
    - export RELEASE=simple
  script:
    - helm install ${RELEASE} . -f test-values/base.yml -f test-values/${RELEASE}.yml
    - helm test --logs ${RELEASE}
    - *test_after
  environment:
    name: simple
    url: https://${RELEASE}.test.magnolia-helm.mirohost.ch

test-full:
  stage: test
  image:
    name: registry.gitlab.com/mironet/helm-kubectl-gomplate
    entrypoint: [ "" ]
  before_script:
    - *test_before
    - export RELEASE=full
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo update
    - helm install ${RELEASE}-minio --set accessKey=fulltest,secretKey=fulltest stable/minio
  script:
    - helm install ${RELEASE} . -f test-values/base.yml -f test-values/${RELEASE}.yml
    - helm test --logs ${RELEASE}
    - *test_after
    - helm del ${RELEASE}-minio
  environment:
    name: full
    url: https://${RELEASE}.test.magnolia-helm.mirohost.ch

upload:
  stage: deploy
  image:
    name: registry.gitlab.com/mironet/helm-kubectl-gomplate
    entrypoint: [""]
  before_script:
    - apk add curl
    - *test_before
  script:
    - helm dep build
    - helm package .
    - curl -f -u "$CHARTMUSEUM_USER:$CHARTMUSEUM_PASS" --data-binary @magnolia-helm-${CHART_VERSION}.tgz https://charts.mirohost.ch/api/charts
  only:
    - tags
