# Default values for magnolia-helm.
# Declare variables to be passed into your templates.

image:
  tomcat:
    repository: tomcat
    tag: 9-jre11-slim
  pullSecrets: []
nameOverride: ""
fullnameOverride: ""

timezone: Europe/Zurich

deploy:
  directory: /usr/local/tomcat/webapps

bootstrap:
  enabled: false

sharedDb:
  enabled: false
  workspaces: []
  db:
    enabled: true
    repository: postgres
    tag: 11.5-alpine
    type: postgres
    name: cluster
    persistence:
      enabled: true
      size: 10Gi
      # accessModes:
      #   - ReadWriteOnce

# This is the author's configuration. It should not use H2 data base (the
# default).
magnoliaAuthor:
  restartPolicy: Always
  webarchive:
    repository: registry.gitlab.com/mironet/magnolia-demo
    tag: latest
  rescueMode: false
  setenv:
    memory:
      minPercentage: 25
      maxPercentage: 80
    update:
      auto: "true"
  resources:
    requests:
      memory: 512Mi
    limits:
      #cpu: 1000m
      memory: 512Mi
  logging:
    level: DEBUG
    pattern: "%d %-5p %-50.50c: %m%n"
  bootstrap:
    password: ""
  activation:
    privateKey: null
    publicKey: null
    # Set this to `true` in case you want to use an existing activation key
    # stored as a secret and provide its name.
    useExistingSecret: False
    keyLocation: /keys/activation/magnolia-activation-keypair.properties
    secret:
      name: my-activation-secret
      key: my-activation-secret-key # The name of they inside the secret to use.
  db:
    enabled: true
    repository: postgres
    tag: 11.5-alpine
    type: postgres
    name: author
    persistence:
      enabled: true
      size: 10Gi
      # accessModes:
      #   - ReadWriteOnce

      # existingClaim: test  # Use this claim if you want to reuse an existing PVC.

# This is the public instance. It can use the H2 data base, but it's also
# supported to use PostgreSQL / MySQL if needed.
magnoliaPublic:
  restartPolicy: Always
  webarchive:
    repository: registry.gitlab.com/mironet/magnolia-demo
    tag: latest
  rescueMode: false
  setenv:
    memory:
      minPercentage: 25
      maxPercentage: 80
    update:
      auto: "true"
  resources:
    requests:
      memory: 512Mi
    limits:
      #cpu: 1000m
      memory: 512Mi
  logging:
    level: DEBUG
    pattern: "%d %-5p %-50.50c: %m%n"
  bootstrap:
    password: ""
  activation:
    privateKey: null
    publicKey: null
    # Set this to `true` in case you want to use an existing activation key
    # stored as a secret and provide its name.
    useExistingSecret: False
    keyLocation: /keys/activation/magnolia-activation-keypair.properties
    secret:
      name: my-activation-secret
      key: my-activation-secret-key # The name of they inside the secret to use.
  db:
    enabled: true # If false, use embedded H2 data base.
    repository: postgres
    tag: 11.5-alpine
    type: postgres
    name: public
    persistence:
      enabled: true
      size: 10Gi
  livenessProbe:
    path: /
    port: 8080
    failureThreshold: 4
    periodSeconds: 30

# Additional jars which should be loaded into tomcat can be specified here.
jars:
  - name: postgres-jdbc
    repository: registry.gitlab.com/mironet/magnolia-jar
    tag: postgres-42.2.8
    env:
      - name: INIT_DEST
        value: /app/magnolia/WEB-INF/lib
    initScript: /init.sh

service:
  annotations: {}
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

ingress:
  enabled: False
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    # Use these if you want cert-manager to issue let's encrypt certs.
    #cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts: []
    # Specify hosts here as an array.
    # - host: k8s.local
    #   paths:
    #     - path: /
    #       instance: author

  tls: []
    # # Specify hosts here if you want to use TLS.
    # - hosts:
    #   - k8s.local
    #   # # Specify a secret name here if you already have a cert stored in the
    #   # # and know its name. If this is not specified, let's encrypt will be used
    #   # # to issue a new certificate.
    #   # secretName: supersecret-cert

# Configuration for the bootstrapper. The idea is to fix the specific version
# tested with this chart.
postjob:
  image: registry.gitlab.com/mironet/magnolia-bootstrap
  tag: v0.1.7


resources: {}

nodeSelector: {}

affinity: {}
