{{- if .Values.magnoliaAuthor.db -}}
{{- $fullName := include "magnolia.fullname" . -}}
{{- $name := include "magnolia.name" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $db := .Values.magnoliaAuthor.db -}}
{{- $appName := printf "%s-%s-db" $fullName $db.name -}}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $appName }}
    chart: {{ $chartName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ $db.name }}-db
          emptyDir: {}
      containers:
        - name: {{ $db.name }}-db
          image: "{{ $db.repository }}:{{ $db.tag }}"
          {{- if eq $db.type "postgres" }}
          env:
            - name: POSTGRES_DB
              value: "{{ $db.name }}"
          {{ end }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ $appName }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.service.annotations }}
    annotations:
        {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
    type: "{{ .Values.service.type }}"
    clusterIP: None
    selector:
        app: {{ $appName }}
        release: {{ .Release.Name }}
    ports:
    {{- if eq $db.type "postgres" }}
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    {{- end }}
{{- end -}}