{{- $fullName := include "magnolia.fullname" . -}}
{{- $name := include "magnolia.name" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $labels := include "magnolia.labels" . -}}
{{- range list (dict "mode" "author" "values" .Values.magnoliaAuthor) (dict "mode" "public" "values" .Values.magnoliaPublic) -}}
{{- $magnoliaMode := .mode -}}
{{- $name := printf "%s-%s" $fullName $magnoliaMode -}}
{{- $db := .values.db -}}
{{- $dbHost := printf "%s-%s-db" $fullName $db.name -}}
{{- $data := dict "Template" $.Template "Values" $.Values "dbHost" $dbHost "db" $db "name" $name "magnoliaMode" $magnoliaMode -}}
{{- $logging := dict "Template" $.Template "Values" $.Values "pattern" .values.logging.pattern "level" .values.logging.level "loggers" .values.logging.loggers -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap-%s" $.Release.Name $magnoliaMode }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ $labels | indent 4 }}
data:
{{- with .values.setenv }}
  JVM_RAM_MIN_PERCENTAGE: {{ default 25 .memory.minPercentage | quote }}
  JVM_RAM_MAX_PERCENTAGE: {{ default 80 .memory.maxPercentage | quote }}
  MGNL_AUTO_UPDATE: {{ default "true" .update.auto | quote }}
{{- end }}
  MGNL_AUTHOR_INSTANCE: {{ eq $magnoliaMode "public" | ternary "false" "true" | quote }}
  server.xml: |-
{{ tpl ($.Files.Get "files/server.xml") $data | indent 4 }}
{{- with $db }}
  jackrabbit.xml: |-
{{ tpl (printf "files/%s.xml" .type | $.Files.Get) $data | indent 4 }}
{{ if .clustering }}
  jackrabbit-shared.xml: |-
{{ tpl (printf "files/%s-shared.xml" .type | $.Files.Get) $data | indent 4 }}
{{- end }}
  log4j2.xml: |-
{{ tpl ($.Files.Get "files/log4j2.xml") $logging | indent 4 }}
  setenv.sh: |-
{{ tpl ($.Files.Get "files/setenv.sh") $data | indent 4 }}
{{ end -}}
{{- end }}
