{{- $dbHost := printf "%s-db" (include "magnolia.fullname" . ) -}}
{{- $data := dict "Template" .Template "Values" .Values "dbHost" $dbHost -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-{{ .Values.magnolia.author | ternary "author" "public" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- template "magnolia.labels" . }}
data:
  magnolia.properties: |-
{{ tpl (.Files.Get "files/magnolia.properties" ) $data | indent 4 }}
{{- if .Values.db }}
  jackrabbit.xml: |-
{{ tpl (printf "files/%s.xml" .Values.magnolia.repository.type | .Files.Get) $data | indent 4 }}
{{ end -}}