{{- $fullName := include "magnolia.fullname" . -}}
{{- range list .Values.magnoliaAuthor .Values.magnoliaPublic -}}
{{- if and .db.contentsync.enabled .db.enabled -}}
{{- $appName := printf "%s-%s-db" $fullName .db.name -}}
{{- $dbName := printf "%s-db" .db.name }}
---
# This is our client cert used for all magnolia-backup clients to request new
# base backups on-demand.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $appName }}-cs-cert
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "magnolia.labels" $ | nindent 4 }}
spec:
  secretName: {{ $appName }}-client-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "*.{{ $appName }}.{{ $.Release.Namespace }}.svc.cluster.local"
  - "*.{{ $appName }}.{{ $.Release.Namespace }}"
  - "*.{{ $appName }}"
  duration: 43800h # 5y
  renewBefore: 1440h # 60d
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $fullName }}-selfsigned-issuer
---
{{- end -}}
{{- end -}}
