{{- $fullName := include "magnolia.fullname" . -}}
{{- $name := include "magnolia.name" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $release := .Release -}}
{{- range list .Values.magnoliaAuthor.db .Values.magnoliaPublic.db (.Values.sharedDb.enabled | ternary .Values.sharedDb.db nil)  -}}
{{- if . -}}
{{- $appName := printf "%s-%s-db" $fullName .name -}}
{{- $dbName := printf "%s-db" .name }}
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ $appName }}
  namespace: {{ $release.Namespace }}
  labels:
    app: {{ $appName }}
    chart: {{ $chartName }}
    release: {{ $release.Name }}
    heritage: {{ $release.Service }}
    component: {{ .name }}
spec:
  serviceName: {{ $appName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appName }}
      release: {{ $release.Name }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        release: {{ $release.Name }}
        tier: database
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                    - database
                - key: release
                  operator: In
                  values:
                    - {{ $.Release.Name }}
      containers:
        - name: {{ $dbName }}
          image: "{{ .repository }}:{{ .tag }}"
{{- if eq .type "postgres" }}
          env:
            - name: POSTGRES_DB
              value: "{{ .name }}"
{{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
{{- if and .persistence.enabled .persistence.existingClaim }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .persistence.existingClaim }}
{{- else if not .persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
{{- else if and .persistence.enabled (not .persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ $appName }}
          chart: {{ $chartName }}
          release: {{ $release.Name }}
          heritage: {{ $release.Service }}
          component: {{ .name }}
      spec:
        resources:
          requests:
            storage: {{ .persistence.size | default "10Gi" | quote }}
        storageClassName: {{ .persistence.storageClassName }}
        accessModes:
      {{- if .persistence.accessModes }}
          {{- toYaml .persistence.accessModes | nindent 10 }}
      {{- else }}
          - ReadWriteOnce
      {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ $appName }}
    namespace: {{ $release.Namespace }}
    {{- if $.Values.service.annotations }}
    annotations:
        {{- toYaml $.Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
    type: "{{ $.Values.service.type }}"
    clusterIP: None
    selector:
        app: {{ $appName }}
        release: {{ $release.Name }}
    ports:
    {{- if eq .type "postgres" }}
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    {{- end }}
{{- end }}
{{- end -}}
