{{- if .Values.bootstrap.enabled }}
{{- $fullName := include "magnolia.fullname" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $name := $fullName -}}
{{- $labels := include "magnolia.labels" . -}}
{{- $data := include "magnolia.labels" . -}}
{{- range list (dict "mode" "author" "values" .Values.magnoliaAuthor) (dict "mode" "public" "values" .Values.magnoliaPublic) -}}
{{- $magnoliaMode := .mode }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-bootstrap-%s" $.Release.Name $magnoliaMode }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ $labels | indent 4 }}
data:
{{- if .values.bootstrap.instructions }}
  instructions.yml: |-
{{ .values.bootstrap.instructions | indent 4 }}
{{- else }}
  instructions.yml: |-
{{ $.Files.Get (printf "files/bootstrap/%s.yml" $magnoliaMode) | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
