{{- if .Values.bootstrap.enabled -}}
{{- $fullName := include "magnolia.fullname" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $name := $fullName -}}
{{- $labels := include "magnolia.labels" . -}}
{{- $data := include "magnolia.labels" . -}}
{{- range list (dict "mode" "author" "values" .Values.magnoliaAuthor) (dict "mode" "public" "values" .Values.magnoliaPublic) -}}
{{- $magnoliaMode := .mode -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-%s" $.Release.Name "secret-superuser" $magnoliaMode }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ $labels | indent 4 }}
type: Opaque
data:
  password: {{ if .values.bootstrap.password }}{{ .values.bootstrap.password | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{ end -}}
{{- end }}