{{- $fullName := include "magnolia.fullname" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bootstrapper-sa
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $fullName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bootstrapper-r
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $fullName }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - namespaces
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bootstrapper-rb
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: bootstrapper-r
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: bootstrapper-sa
    namespace: {{ $.Release.Namespace }}
---