{{- $fullName := include "magnolia.fullname" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $name := printf "%s-%s" $fullName "public" -}}
{{- $pub := .Values.magnoliaPublic }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "magnolia.labels" . | nindent 4 }}
    tier: app
    component: public-instance
spec:
  serviceName: {{ $name }}-svc
  replicas: {{ $pub.replicas }}
  selector:
    matchLabels:
      {{- include "magnolia.labels" . | nindent 6 }}
      tier: app
      component: public-instance
  template:
    metadata:
      labels:
        {{- include "magnolia.labels" . | nindent 8 }}
        tier: app
        component: public-instance
      annotations:
        {{- if $pub.redeploy }}
        timestamp: "{{ date "20060102150405" now }}"
        {{- end }}
    spec:
      securityContext:
        {{- toYaml $.Values.deploy.securityContext | nindent 8 }}
      restartPolicy: {{ $pub.restartPolicy | default "Always" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  release: {{ $.Release.Name }}
                  tier: database
                  component: {{ $pub.db.name }}
      volumes:
        - name: temp
          emptyDir: {}
        - name: magnolia-home
          persistentVolumeClaim:
        {{- if $pub.persistence.enabled }}
        {{- if $pub.persistence.existingClaim }}
            claimName: {{ $pub.persistence.existingClaim }}
        {{- end }}
        {{- end }}
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/{{ $.Values.timezone }}
        - name: app
          emptyDir: {}
{{- if $pub.db.enabled }}
        - name: jackrabbit-config
          configMap:
            items:
            - key: jackrabbit.xml
              mode: 420
              path: jackrabbit.xml
            name: {{ $.Release.Name }}-configmap-public
            optional: False
{{- if $.Values.sharedDb.enabled }}
        - name: jackrabbit-shared-config
          configMap:
            items:
              - key: jackrabbit-shared.xml
                mode: 420
                path: jackrabbit-shared.xml
            name: {{ $.Release.Name }}-configmap-public
            optional: False
        - name: jcr-repositories
          configMap:
            items:
              - key: jcr-repositories.xml
                mode: 420
                path: jcr-repositories.xml
            name: {{ $.Release.Name }}-configmap-public
            optional: False
{{- end }}
{{- if $pub.rescueMode }}
        - name: rescue-web-xml
          configMap:
            items:
              - key: rescue-web.xml
                mode: 420
                path: rescue-web.xml
            name: {{ $.Release.Name }}-configmap-public
            optional: False
{{- end }}
{{- end }}
        - name: log4j-config
          configMap:
            items:
              - key: log4j2.xml
                mode: 420
                path: log4j2.xml
            name: {{ $.Release.Name }}-configmap-public
            optional: False
        - name: setenv
          configMap:
            items:
            - key: setenv.sh
              mode: 420
              path: setenv.sh
            name: {{ $.Release.Name }}-configmap-public
            optional: False
        - name: server-xml
          configMap:
            items:
            - key: server.xml
              mode: 420
              path: server.xml
            name: {{ $.Release.Name }}-configmap-public
            optional: False
        - name: logging-properties
          configMap:
            items:
            - key: logging.properties
              mode: 420
              path: logging.properties
            name: {{ $.Release.Name }}-configmap-public
            optional: False
        {{- if $.Values.bootstrap.enabled }}
        - name: instructions
          configMap:
            items:
            - key: instructions.yml
              mode: 420
              path: instructions.yml
            name: {{ printf "%s-bootstrap-%s" $.Release.Name "public" }}
            optional: False
        {{- end }}
      initContainers:
        - name: war
          image: {{ $pub.webarchive.repository }}:{{ $pub.webarchive.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["sh", "-c", "cp -a /magnolia /app/"]
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: app
              mountPath: /app
        {{- range $.Values.jars }}
        - name: {{ .name }}
          image: {{ .repository }}:{{ .tag }}
          command:
            - {{ .initScript }}
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: app
              mountPath: /app
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end -}}
        {{- end }}
        - name: dyn-dbconfig
          image: {{ printf "%s:%s" $.Values.postjob.image $.Values.postjob.tag }}
          imagePullPolicy: {{ $.Values.postjob.imagePullPolicy }}
          command:
            - /app
            - template
            - -i
            - /data/jackrabbit.xml
            - -o
            - /magnolia/magnolia/WEB-INF/config/repo-conf/jackrabbit.xml
          volumeMounts:
            - name: jackrabbit-config
              mountPath: /data/jackrabbit.xml
              subPath: jackrabbit.xml
            - name: app
              mountPath: /magnolia
        - name: waitfor-db
          image: {{ printf "%s:%s" $.Values.postjob.image $.Values.postjob.tag }}
          imagePullPolicy: {{ $.Values.postjob.imagePullPolicy }}
          {{- $dbHost := printf "%s-%s-db" $fullName $pub.db.name }}
          command:
            - /app
            - waitfor
            - --names
            - {{ $dbHost }}-{{ "{{ .Env.HOSTNAME | podordinal }}" }}.{{ $dbHost }}
      containers:
        - name: {{ $.Chart.Name }}
          image: {{ $.Values.image.tomcat.repository }}:{{ $.Values.image.tomcat.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- with $pub.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
        {{- with $pub.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configmap-%s" $.Release.Name "public" }}
                optional: false
          volumeMounts:
            - name: temp
              mountPath: {{ $.Values.deploy.tempDir }}
            - name: tz-config
              mountPath: /etc/localtime
            - name: magnolia-home
              mountPath: {{ $pub.persistence.mountPath | default "/mgnl-home" }}
            - name: app
              mountPath: {{ $.Values.deploy.directory }}
{{- if $pub.db.enabled }}
{{- if $pub.rescueMode }}
            - name: rescue-web-xml
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/web.xml
              subPath: rescue-web.xml
{{- end }}
{{- if $.Values.sharedDb.enabled }}
            - name: jackrabbit-shared-config
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/config/repo-conf/jackrabbit-shared.xml
              subPath: jackrabbit-shared.xml
            - name: jcr-repositories
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/config/default/repositories.xml
              subPath: jcr-repositories.xml
{{- end }}
{{- end }}
            - name: log4j-config
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/config/default/log4j2.xml
              subPath: log4j2.xml
            - name: setenv
              mountPath: /usr/local/tomcat/bin/setenv.sh
              subPath: setenv.sh
            - name: server-xml
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
            - name: logging-properties
              mountPath: /usr/local/tomcat/conf/logging.properties
              subPath: logging.properties
        - name: bootstrapper
          image: {{ printf "%s:%s" $.Values.postjob.image $.Values.postjob.tag }}
          imagePullPolicy: {{ $.Values.postjob.imagePullPolicy }}
          command:
            - /app
            - serve
            - -m
            - http://localhost:8080{{ $pub.contextPath }}
            - --code
            - "{{ $pub.livenessProbe.expectedCodes }}"
            {{- if $.Values.bootstrap.enabled }}
            - -i
            - /data/instructions.yml
            {{- end }}
            #- -vvv  # Trace mode.
          volumeMounts:
            - name: app
              mountPath: /magnolia
            {{- if $.Values.bootstrap.enabled }}
            - name: instructions
              mountPath: /data/instructions.yml
              subPath: instructions.yml
            {{- end }}
          env:
          {{- if $.Values.bootstrap.enabled }}
          - name: MGNLBOOT_NEW_SUPERUSER_PW
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ printf "%s-%s-%s" $.Release.Name "secret-superuser" "public" }}
          - name: MGNLBOOT_AUTHOR_SUPERUSER_PW
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ printf "%s-%s-%s" $.Release.Name "secret-superuser" "author" }}
          - name: MGNL_CONTEXT_PATH
            value: {{ $pub.contextPath }}
          - name: MGNLBOOT_AUTHOR_INSTANCE
            value: {{ printf "http://%s-%s-svc:8080%s" $fullName "author" $.Values.magnoliaAuthor.contextPath }}
          - name: MGNLBOOT_PUBLIC_SERVICE_NAME
            value: {{ printf "%s-%s-svc" $fullName "public" }}
          - name: MGNL_PODNAME
            value: {{ $name }}
          {{- if $pub.base_url }}
          - name: MGNL_DEFAULT_BASE_URL
            value: {{ $pub.base_url | quote }}
          {{- end }}
          {{- if $pub.activation.useExistingSecret }}
          - name: MGNL_ACTIVATION_PUBKEY
            valueFrom:
              secretKeyRef:
                name:  {{ $pub.activation.secret.name | quote }}
                key:  {{ $pub.activation.secret.key| quote }}
          {{- end }}
          {{- end }}
          {{- if $pub.livenessProbe.enabled }}
          {{- $contextPath := $pub.contextPath }}
          {{- with $pub.livenessProbe }}
          ports:
            - name: "liveness-port"
              containerPort: 8765
          livenessProbe:
            httpGet:
              path: /healthz
              port: "liveness-port"
            failureThreshold: {{ .failureThreshold | default 4 }}
            periodSeconds: {{ .periodSeconds | default 30 }}
            timeoutSeconds: {{ .timeoutSeconds | default 10 }}
            initialDelaySeconds: {{ .initialDelaySeconds | default 240 }}
          {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: "liveness-port"
            initialDelaySeconds: 2
            #periodSeconds: 120
            timeoutSeconds: 2
            successThreshold: 3
        {{- with $pub.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- if $.Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml $.Values.image.pullSecrets | nindent 8 }}
    {{- end }}
    {{- if $.Values.nodeSelector }}
      nodeSelector:
      {{- toYaml $.Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if $.Values.tolerations }}
      tolerations:
      {{- toYaml $.Values.tolerations | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - spec:
        resources:
          requests:
            storage: {{ $pub.db.backup.pg_wal_archive_size | default "50Gi" }}
        storageClassName: {{ $pub.db.backup.pg_wal_storageClassName | default "" }}
        accessModes:
          - ReadWriteOnce
      metadata:
        name: archive
        labels:
          {{- include "magnolia.labels" . | nindent 10 }}
          tier: app
          component: public-instance
    {{- if $pub.persistence.enabled }}
    - spec:
        resources:
          requests:
            storage: {{ $pub.persistence.size | default "10Gi" }}
        storageClassName: {{ $pub.persistence.storageClassName | default "" }}
        accessModes:
          - ReadWriteOnce
      metadata:
        name: home
        labels:
          {{- include "magnolia.labels" . | nindent 10 }}
          tier: app
          component: public-instance
    {{- end }}
