{{- if $.Values.magnoliaCombined.enabled -}}
{{- $fullName := include "magnolia.fullname" . -}}
{{- $chartName := include "magnolia.chart" . -}}
{{- $name := printf "%s-%s" $fullName "combined" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "magnolia.labels" $ | nindent 4 }}
    tier: app
    component: combined-instance
spec:
  serviceName: {{ $name }}-svc
  replicas: 1
  selector:
    matchLabels:
      {{- include "magnolia.labels" $ | nindent 6 }}
      tier: app
      component: combined-instance
  template:
    metadata:
      labels:
        {{- include "magnolia.labels" $ | nindent 8 }}
        tier: app
        component: combined-instance
      annotations:
{{- if and $.Values.metrics.enabled $.Values.metrics.setPrometheusAnnotations }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ $.Values.metrics.metricsServerPort }}"
{{- end }}
        {{- if $.Values.magnoliaCombined.redeploy }}
        timestamp: "{{ date "20060102150405" now }}"
        {{- end }}
        {{- range $key, $value := $.Values.magnoliaCombined.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml $.Values.deploy.securityContext | nindent 8 }}
      restartPolicy: {{ $.Values.magnoliaCombined.restartPolicy | default "Always" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  release: {{ $.Release.Name }}
                  tier: database
                  component: {{ $.Values.magnoliaCombined.db.name }}
      volumes:
        - name: temp
          emptyDir: {}
        - name: magnolia-home
        {{- if and $.Values.magnoliaCombined.persistence.enabled $.Values.magnoliaCombined.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ $.Values.magnoliaCombined.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/{{ $.Values.timezone }}
        - name: app
          emptyDir: {}
        # This volume's name has to conform to the rules for a dns name.
        - name: extralibs
          emptyDir: {}
{{- if $.Values.metrics.enabled }}
        - name: jmx-exporter-config
          configMap:
            items:
            - key: jmx-exporter-config.yml
              mode: 420
              path: config.yml
            name: {{ $.Release.Name }}-configmap-combined
            optional: False
{{- end }}
{{- if $.Values.magnoliaCombined.db.enabled }}
        - name: jackrabbit-config
          configMap:
            items:
            - key: jackrabbit.xml
              mode: 420
              path: jackrabbit.xml
            name: {{ $.Release.Name }}-configmap-combined
            optional: False
{{- end }}
{{- if or .rescueMode .rescueModeDX }}
        - name: rescue-web-xml
          configMap:
            items:
              - key: rescue-web.xml
                mode: 420
                path: rescue-web.xml
            name: {{ $.Release.Name }}-configmap-combined
            optional: False
{{- end }}
        - name: log4j-config
          configMap:
            items:
              - key: log4j2.xml
                mode: 420
                path: log4j2.xml
            name: {{ $.Release.Name }}-configmap-combined
            optional: False
        - name: setenv
          configMap:
            items:
            - key: setenv.sh
              mode: 420
              path: setenv.sh
            name: {{ $.Release.Name }}-configmap-combined
            optional: False
        - name: server-xml
          configMap:
            items:
            - key: server.xml
              mode: 420
              path: server.xml
            name: {{ $.Release.Name }}-configmap-combined
            optional: False
        - name: logging-properties
          configMap:
            items:
            - key: logging.properties
              mode: 420
              path: logging.properties
            name: {{ $.Release.Name }}-configmap-combined
            optional: False

        {{- if $.Values.bootstrap.enabled }}
        - name: instructions
          configMap:
            items:
            - key: instructions.yml
              mode: 420
              path: instructions.yml
            name: {{ printf "%s-bootstrap-combined" $.Release.Name }}
            optional: False
        {{- end }}
      initContainers:
        - name: war
          image: {{ $.Values.magnoliaCombined.webarchive.repository }}:{{ $.Values.magnoliaCombined.webarchive.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["sh", "-c", "cp -a /magnolia /app/"]
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: app
              mountPath: /app
        {{- range $.Values.jars }}
        - name: {{ .name }}
          image: {{ .repository }}:{{ .tag }}
          command:
            - {{ .initScript }}
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: app
              mountPath: /app
            - name: extralibs
              mountPath: /extraLibs
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end -}}
        {{- end }}
        {{- with .extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: dyn-dbconfig
          image: {{ printf "%s:%s" $.Values.postjob.image $.Values.postjob.tag }}
          imagePullPolicy: {{ $.Values.postjob.imagePullPolicy }}
          command:
            - /app
            - template
            - -i
            - /data/jackrabbit.xml
            - -o
            - /magnolia/magnolia/WEB-INF/config/repo-conf/jackrabbit.xml
          volumeMounts:
            - name: jackrabbit-config
              mountPath: /data/jackrabbit.xml
              subPath: jackrabbit.xml
            - name: app
              mountPath: /magnolia
        - name: waitfor-db
          image: {{ printf "%s:%s" $.Values.postjob.image $.Values.postjob.tag }}
          imagePullPolicy: {{ $.Values.postjob.imagePullPolicy }}
          {{- $dbHost := printf "%s-%s-db" $fullName $.Values.magnoliaCombined.db.name }}
          command:
            - /app
            - waitfor
            - --names
            - {{ $dbHost }}-{{ "{{ .Env.HOSTNAME | podordinal }}" }}.{{ $dbHost }}
      containers:
        - name: {{ $.Release.Name }}
          image: {{ $.Values.image.tomcat.repository }}:{{ $.Values.image.tomcat.tag }}
          imagePullPolicy: {{ $.Values.image.tomcat.pullPolicy }}
        {{- with $.Values.magnoliaCombined.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
        {{- with $.Values.magnoliaCombined.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configmap-combined" $.Release.Name }}
                optional: false
          volumeMounts:
            - name: temp
              mountPath: {{ $.Values.deploy.tempDir }}
            - name: tz-config
              mountPath: /etc/localtime
            - name: magnolia-home
              mountPath: {{ $.Values.magnoliaCombined.persistence.mountPath | default "/mgnl-home" }}
            - name: app
              mountPath: {{ $.Values.deploy.directory }}
            - name: extralibs
              mountPath: {{ $.Values.deploy.extraLibs }}
{{- if .db.enabled }}
{{- if or .rescueMode .rescueModeDX }}
            - name: rescue-web-xml
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/web.xml
              subPath: rescue-web.xml
{{- end }}
{{- if $.Values.sharedDb.enabled }}
            - name: jackrabbit-shared-config
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/config/repo-conf/jackrabbit-shared.xml
              subPath: jackrabbit-shared.xml
            - name: jcr-repositories
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/config/default/repositories.xml
              subPath: jcr-repositories.xml
{{- end }}
{{- end }}
            - name: log4j-config
              mountPath: /usr/local/tomcat/webapps/magnolia/WEB-INF/config/default/log4j2.xml
              subPath: log4j2.xml
            - name: setenv
              mountPath: /usr/local/tomcat/bin/setenv.sh
              subPath: setenv.sh
            - name: server-xml
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
            - name: logging-properties
              mountPath: /usr/local/tomcat/conf/logging.properties
              subPath: logging.properties
            - name: jmx-exporter-config
              mountPath: /jmxexporter/config.yml
              subPath: config.yml

        - name: bootstrapper
          image: {{ printf "%s:%s" $.Values.postjob.image $.Values.postjob.tag }}
          imagePullPolicy: {{ $.Values.postjob.imagePullPolicy }}
          command:
            - /app
            - serve
            - -m
            - http://localhost:8080{{ $.Values.magnoliaCombined.contextPath }}
            - --code
            - "{{ $.Values.magnoliaCombined.livenessProbe.expectedCodes }}"
            {{- if $.Values.bootstrap.enabled }}
            - -i
            - /data/instructions.yml
            - --path
            - "{{ .livenessProbe.path }}"
            {{- end }}
            #- -vvv  # Trace mode.
          volumeMounts:
            - name: app
              mountPath: /magnolia
            {{- if $.Values.bootstrap.enabled }}
            - name: instructions
              mountPath: /data/instructions.yml
              subPath: instructions.yml
            {{- end }}
          env:
          {{- if $.Values.bootstrap.enabled }}
          - name: MGNLBOOT_SUPERUSER_NAME
            value: {{ $.Values.magnoliaCombined.bootstrap.username }}

          - name: MGNLBOOT_NEW_SUPERUSER_PW
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ printf "%s-%s-combined" $.Release.Name "secret-superuser" }}
          - name: MGNLBOOT_AUTHOR_SUPERUSER_PW
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ printf "%s-%s-%s" $.Release.Name "secret-superuser" "author" }}
          - name: MGNL_CONTEXT_PATH
            value: {{ $.Values.magnoliaCombined.contextPath }}
          - name: MGNLBOOT_AUTHOR_INSTANCE
            value: {{ printf "http://%s-%s-svc:8080%s" $fullName "author" $.Values.magnoliaAuthor.contextPath }}
          - name: MGNLBOOT_PUBLIC_SERVICE_NAME
            value: {{ printf "%s-%s-svc" $fullName "public" }}
          - name: MGNL_PODNAME
            value: {{ $name }}
          {{- if $.Values.magnoliaCombined.base_url }}
          - name: MGNL_DEFAULT_BASE_URL
            value: {{ $.Values.magnoliaCombined.base_url | quote }}
          {{- end }}
          {{- if $.Values.magnoliaCombined.activation.useExistingSecret }}
          - name: MGNL_ACTIVATION_PUBKEY
            valueFrom:
              secretKeyRef:
                name:  {{ $.Values.magnoliaCombined.activation.secret.name | quote }}
                key:  {{ $.Values.magnoliaCombined.activation.secret.key| quote }}
          {{- end }}
          {{- if $.Values.magnoliaCombined.bootstrap.extraEnv }}
          {{- toYaml $.Values.magnoliaCombined.bootstrap.extraEnv | nindent 10 }}
          {{- end }}
          {{- end }}
          ports:
            - name: "liveness-port"
              containerPort: 8765
          {{- if $.Values.magnoliaCombined.livenessProbe.enabled }}
          {{- $contextPath := $.Values.magnoliaCombined.contextPath }}
          {{- with $.Values.magnoliaCombined.livenessProbe }}
          livenessProbe:
            httpGet:
              path: /livez
              port: "liveness-port"
            failureThreshold: {{ .failureThreshold | default 4 }}
            periodSeconds: {{ .periodSeconds | default 30 }}
            timeoutSeconds: {{ .timeoutSeconds | default 10 }}
            initialDelaySeconds: {{ .initialDelaySeconds | default 240 }}
          {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: "liveness-port"
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
        {{- with $.Values.magnoliaCombined.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- if $.Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml $.Values.image.pullSecrets | nindent 8 }}
    {{- end }}
    {{- if $.Values.nodeSelector }}
      nodeSelector:
      {{- toYaml $.Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if $.Values.tolerations }}
      tolerations:
      {{- toYaml $.Values.tolerations | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - spec:
        resources:
          requests:
            storage: {{ $.Values.magnoliaCombined.db.backup.pg_wal_archive_size | default "50Gi" }}
        storageClassName: {{ $.Values.magnoliaCombined.db.backup.pg_wal_storageClassName | default "" }}
        accessModes:
          - ReadWriteOnce
      metadata:
        name: archive
        labels:
          {{- include "magnolia.labels" $ | nindent 10 }}
          tier: app
          component: combined-instance
    {{- if $.Values.magnoliaCombined.persistence.enabled }}
    - spec:
        resources:
          requests:
            storage: {{ $.Values.magnoliaCombined.persistence.size | default "10Gi" }}
        storageClassName: {{ $.Values.magnoliaCombined.persistence.storageClassName | default "" }}
        accessModes:
          - ReadWriteOnce
      metadata:
        name: magnolia-home
        labels:
          {{- include "magnolia.labels" $ | nindent 10 }}
          tier: app
          component: combined-instance
    {{- end }}
{{- end }}
