---
bootstrap:
  enabled: True

magnoliaAuthor:
  resources:
    requests:
      memory: 2Gi
    limits:
      #cpu: 1000m
      memory: 2Gi

magnoliaPublic:
  resources:
    requests:
      memory: 2Gi
    limits:
      #cpu: 1000m
      memory: 2Gi